name = "cbp"

main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

workers_dev = false
route = { pattern = "cbp.ngo.sh", custom_domain = true }

[site]
  bucket = "./public"

[build]
  command = "npm run build"
